# Generated by Django 4.0.3 on 2024-06-04 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='item',
            name='cantidad_stock',
            field=models.IntegerField(verbose_name='Cantidad en stock'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='monto_total',
            field=models.FloatField(default=0, verbose_name='Monto total'),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='cantidad_seleccionada',
            field=models.IntegerField(default=1, verbose_name='Cantidad seleccionada'),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_item', to='carta.pedido'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='cantidad_personas',
            field=models.IntegerField(verbose_name='Cantidad de personas'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_hora',
            field=models.DateTimeField(verbose_name='Fecha y hora'),
        ),
    ]
