# Generated by Django 4.0.3 on 2024-06-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carta', '0002_alter_cliente_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='foto',
            field=models.ImageField(blank=True, default='/static/imagenes/empty.jpg', upload_to='items/', verbose_name='foto'),
        ),
    ]
