# Generated by Django 4.0.3 on 2024-06-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carta', '0003_alter_item_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='foto',
            field=models.ImageField(blank=True, default='/empty.jpg', upload_to='items/', verbose_name='foto'),
        ),
    ]
