# Generated by Django 4.0.3 on 2024-08-06 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carta', '0007_historialpedido_pedido_completado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialpedidoitem',
            name='historial_pedido',
        ),
        migrations.RemoveField(
            model_name='historialpedidoitem',
            name='producto',
        ),
        migrations.DeleteModel(
            name='HistorialPedido',
        ),
        migrations.DeleteModel(
            name='HistorialPedidoItem',
        ),
    ]
