# Generated by Django 4.0.3 on 2024-08-06 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carta', '0008_remove_historialpedidoitem_historial_pedido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('preparacion', 'En preparacion'), ('terminado', 'Terminado'), ('cancelado', 'Cancelado'), ('finalizado', 'Finalizado')], default='preparacion', max_length=12, verbose_name='Estado del Pedido'),
        ),
    ]
