# Generated by Django 4.0.3 on 2024-08-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carta', '0010_pedidoitem_gluten_free_pedidoitem_tradicional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='anotacion_cliente',
            field=models.TextField(blank=True, null=True),
        ),
    ]
