# Generated by Django 4.0.3 on 2024-08-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carta', '0013_alter_pedido_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='pedidoitem',
            name='gluten_free',
        ),
        migrations.RemoveField(
            model_name='pedidoitem',
            name='tradicional',
        ),
        migrations.RemoveField(
            model_name='pedidoitem',
            name='veggie',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('confirmado', 'confirmado'), ('pendiente', 'pendiente de confirmacion'), ('preparacion', 'En preparación'), ('listo_para_entregar', 'Listo para entregar'), ('entregado', 'entregado'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='confirmado', max_length=25, verbose_name='Estado del Pedido'),
        ),
        migrations.DeleteModel(
            name='Descuento',
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
