# Generated by Django 4.0.3 on 2024-08-17 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carta', '0014_remove_reserva_cliente_remove_pedidoitem_gluten_free_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('confirmado', 'Confirmado'), ('preparacion', 'Preparacion'), ('listo_para_entregar', 'Listo para entregar'), ('entregado', 'Entregado'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='confirmado', max_length=25, verbose_name='Estado del Pedido'),
        ),
    ]
