# Generated by Django 4.0.3 on 2024-09-02 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carta', '0016_alter_pedido_estado_estadopedido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstadoPedido',
        ),
    ]
